# Generated by Django 4.2.19 on 2025-02-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='weekly_plan',
            field=models.JSONField(blank=True, help_text='Full week daily workout plan as JSON', null=True),
        ),
    ]
